import localFont from "next/font/local";
import "./globals.css";
import Wrapperlayout from "./Wrapperlayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        <div className="relative z-50">
        {/* <saytv-chat bubble="true" width="30" height="100" authentication="true"></saytv-chat> */}
        </div>
        <Wrapperlayout>{children}</Wrapperlayout>
      </body>
    </html>
  );
}
